<?php 
switch (azul_top('language')) {
    	case 'english':
    		$days = 'days';
    		$hours = 'hours';
    		$minutes = 'minutes';
    		$seconds = 'seconds';
    		$day = 'day';
    		$hour = 'hour';
    		$minute = 'minute';
    		$second = 'second';
    		$input_subscription = 'Enter your email';
    		$go = 'GO';
    		$send = 'Send';
    		$name = 'Name';
    		$email = 'Email';
    		$message = 'Message';
    		$human = 'Are you human?';
    		$number = 'Type the code';
    		$success1 = 'Thanks for your subscription!';
    		$success2 = 'Thanks for your message!';
    		$error1 = 'Insert a valid email address';
    		$error2 = 'You have to fill all the fields';
    		$error3 = 'Type the code correctly';
    		break;
    	case 'spanish':
    		$days = 'dias';
    		$hours = 'horas';
    		$minutes = 'minutos';
    		$seconds = 'segundos';
    		$day = 'dia';
    		$hour = 'hora';
    		$minute = 'minuto';
    		$second = 'segundo';
    		$input_subscription = 'Escribe tu email';
    		$go = 'Enviar';
    		$send = 'Enviar';
    		$name = 'Nombre';
    		$email = 'Email';
    		$message = 'Mensaje';
    		$human = '&#191;Eres humano?';
    		$number = 'Escribe el c&oacute;digo';
    		$success1 = '&#161;Gracias por tu suscripci&oacute;n!';
    		$success2 = '&#161;Gracias por tu mensaje!';
    		$error1 = 'Escribe un email v&aacute;lido';
    		$error2 = 'Tienes que rellenar todos los campos';
    		$error3 = 'Escribe el c&oacute;digo correctamente';
    		break;
    	case 'french':
    		$days = 'journees';
    		$hours = 'heures';
    		$minutes = 'minutes';
    		$seconds = 'secondes';
    		$day = 'jour';
    		$hour = 'heure';
    		$minute = 'minute';
    		$second = 'seconde';
    		$input_subscription = 'Entrez votre e-mail';
    		$go = 'Envoyer';
    		$send = 'Envoyer';
    		$name = 'Nom';
    		$email = 'Email';
    		$message = 'Message';
    		$human = '&#202;tes-vous humain?';
    		$number = 'Tapez le code';
    		$success1 = 'Merci pour votre abonnement!';
    		$success2 = 'Merci pour votre message!';
    		$error1 = 'Ins&eacute;rez une adresse e-mail valide';
    		$error2 = 'Vous devez remplir tous les champs';
    		$error3 = 'Tapez le code correctement';
    		break;
    	case 'german':
    		$days = 'Tage';
    		$hours = 'Stunden';
    		$minutes = 'Minuten';
    		$seconds = 'Sekunden';
    		$day = 'Tag';
    		$hour = 'Stunde';
    		$minute = 'Minute';
    		$second = 'Sekunde';
    		$input_subscription = 'Geben sie ihre E-Mail';
    		$go = 'Absenden';
    		$send = 'Absenden';
    		$name = 'Name';
    		$email = 'Email';
    		$message = 'Nachricht';
    		$human = 'Sind Sie ein Mensch?';
    		$number = 'Code eingeben';
    		$success1 = 'Vielen Dank f&#252;r Ihr Abonnement!';
    		$success2 = 'Vielen Dank f&#252;r Ihre Nachricht!';
    		$error1 = 'Legen Sie eine g&#252;ltige E-Mail-Adresse';
    		$error2 = 'Sie m&#252;ssen alle Felder ausf&#252;llen';
    		$error3 = 'Geben Sie den Code richtig';
    		break;
    	case 'italian':
    		$days = 'giorni';
    		$hours = 'ore';
    		$minutes = 'minuti';
    		$seconds = 'secondi';
    		$day = 'giorno';
    		$hour = 'ora';
    		$minute = 'minuto';
    		$second = 'secondo';
    		$input_subscription = 'Inserisci la tua email';
    		$go = 'Inviare';
    		$send = 'Inviare';
    		$name = 'Nome';
    		$email = 'Email';
    		$message = 'Messaggio';
    		$human = 'Sei umano?';
    		$number = 'Digita il codice';
    		$success1 = 'Grazie per il vostro abbonamento!';
    		$success2 = 'Grazie per il tuo messaggio!';
    		$error1 = 'Inserire un indirizzo email valido';
    		$error2 = '&#200; necessario compilare tutti i campi';
    		$error3 = 'Digitare il codice correttamente';
    		break;
    	case 'portuguese':
    		$days = 'dias';
    		$hours = 'horas';
    		$minutes = 'minutos';
    		$seconds = 'segundos';
    		$day = 'dia';
    		$hour = 'hora';
    		$minute = 'minuto';
    		$second = 'segundo';
    		$input_subscription = 'Digite seu e-mail';
    		$go = 'Enviar';
    		$send = 'Enviar';
    		$name = 'Nome';
    		$email = 'Email';
    		$message = 'Mensagem';
    		$human = 'Voc&#234; &eacute; humano?';
    		$number = 'Digite o c&oacute;digo';
    		$success1 = 'Obrigado pela sua inscri&#231;&#227;o!';
    		$success2 = 'Obrigado por seu mensagem!';
    		$error1 = 'Insira um email v&aacute;lido';
    		$error2 = 'Voc&#234; deve preencher todos os campos';
    		$error3 = 'Escreva o c&oacute;digo corretamente';
    		break;
    	case 'russian':
    		$days = 'дней';
    		$hours = 'часов';
    		$minutes = 'минут';
    		$seconds = 'секунды';
    		$day = 'день';
    		$hour = 'час';
    		$minute = 'минут';
    		$second = 'второй';
    		$input_subscription = 'Введите адрес электронной почты';
    		$send = 'послать';
    		$go = 'послать';
    		$name = 'название';
    		$email = 'E-mail';
    		$message = 'сообщение';
    		$human = 'Вы человек?';
    		$number = 'Введите код';
    		$success1 = 'Спасибо за подписку!';
    		$success2 = 'Спасибо за ваше сообщение!';
    		$error1 = 'Вставьте действующий адрес электронной почты';
    		$error2 = 'Вы должны заполнить все поля';
    		$error3 = 'Введите код правильно';
    		break;
    	default:
    		echo '';
    }

?>